// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVk4Tk1DdUTff6k-pyiRpiRKP5N4zn8fI',
    appId: '1:187080259545:web:2810a526b897320e91cbc8',
    messagingSenderId: '187080259545',
    projectId: 'bookworm-317ec',
    authDomain: 'bookworm-317ec.firebaseapp.com',
    storageBucket: 'bookworm-317ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHPpM3Y6IKdihVu_RGLE2RU1ZKAakvUA',
    appId: '1:187080259545:android:451de4cbd895a12291cbc8',
    messagingSenderId: '187080259545',
    projectId: 'bookworm-317ec',
    storageBucket: 'bookworm-317ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVR4Wt6ePjhNegV8koaWLsfYSaACr_Go',
    appId: '1:187080259545:ios:351b76d719e0478c91cbc8',
    messagingSenderId: '187080259545',
    projectId: 'bookworm-317ec',
    storageBucket: 'bookworm-317ec.appspot.com',
    iosBundleId: 'edu.seattleu.bookwormCpsc5250',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVR4Wt6ePjhNegV8koaWLsfYSaACr_Go',
    appId: '1:187080259545:ios:3eab2404231e209791cbc8',
    messagingSenderId: '187080259545',
    projectId: 'bookworm-317ec',
    storageBucket: 'bookworm-317ec.appspot.com',
    iosBundleId: 'edu.seattleu.bookwormCpsc5250.RunnerTests',
  );
}
